# Generated by Django 4.2 on 2025-05-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('breakfast_start', models.TimeField(blank=True, null=True)),
                ('breakfast_end', models.TimeField(blank=True, null=True)),
                ('lunch_start', models.TimeField(blank=True, null=True)),
                ('lunch_end', models.TimeField(blank=True, null=True)),
                ('dinner_start', models.TimeField(blank=True, null=True)),
                ('dinner_end', models.TimeField(blank=True, null=True)),
                ('breakfast_weight_accepted', models.FloatField(blank=True, null=True)),
                ('lunch_weight_accepted', models.FloatField(blank=True, null=True)),
                ('dinner_weight_accepted', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Weight Condition',
                'verbose_name_plural': 'Weight Conditions',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_num', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('date', models.DateTimeField()),
                ('is_modified', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('secret', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_weights', to='sensor.environmentsensor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
