# Generated by Django 4.2 on 2026-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0002_alter_orderweight_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderweight',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='weightconditions',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
