# Generated by Django 4.2 on 2026-05-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuya_proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuyaproxyapikey',
            name='tuya_user_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
