# Generated by Django 4.2 on 2026-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuya_proxy', '0002_alter_tuyaproxyapikey_tuya_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuyaproxyapikey',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
