# Generated by Django 4.2 on 2025-05-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sn', models.CharField(max_length=255, unique=True)),
                ('heart_beat_time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('clean', 'clean'), ('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment')], default='clean', max_length=255)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('tent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera', to='tent.tent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('clean', 'clean'), ('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentiment_list', models.JSONField(blank=True, null=True)),
                ('sentiment_list_annotator', models.JSONField(blank=True, null=True)),
                ('is_annotated', models.BooleanField(default=False)),
                ('average_sentiment', models.FloatField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address_method', models.CharField(blank=True, max_length=255, null=True)),
                ('host_name', models.CharField(blank=True, max_length=255, null=True)),
                ('time_zone', models.IntegerField(blank=True, null=True)),
                ('hw_platform', models.CharField(blank=True, max_length=255, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sentiment_analysis_history/%Y/%m/%d/')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentiment_analysis', to='camera.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KitchenViolationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('violation', models.BooleanField(default=False)),
                ('violation_list', models.JSONField(blank=True, null=True)),
                ('annotator_status', models.JSONField(blank=True, null=True)),
                ('is_annotated', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='kitchen_violation_history/%Y/%m/%d/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_violation_histories', to='camera.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KitchenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='kitchen_images/%Y/%m/%d/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camera.camera')),
                ('tent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tent.tent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuardPresenceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guard_count', models.IntegerField(default=0)),
                ('present', models.BooleanField(default=False)),
                ('annotator_status', models.CharField(blank=True, choices=[('absent', 'absent'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='', max_length=10)),
                ('is_annotated', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='guard_presence_history/%Y/%m/%d/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_presence_histories', to='camera.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarbageMonitoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_clean', models.BooleanField(default=False)),
                ('annotator_status', models.CharField(blank=True, choices=[('', ''), ('garbage', 'garbage')], default='', max_length=10)),
                ('is_annotated', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='garbage_monitoring_history/%Y/%m/%d/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garbage_monitoring_histories', to='camera.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CounterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sn', models.CharField(max_length=255)),
                ('total_in', models.IntegerField(default=0)),
                ('total_out', models.IntegerField(default=0)),
                ('passby', models.IntegerField(default=0)),
                ('turnback', models.IntegerField(default=0)),
                ('avg_stay_time', models.IntegerField(default=0)),
                ('in_adult', models.IntegerField(default=0)),
                ('out_adult', models.IntegerField(default=0)),
                ('passby_adult', models.IntegerField(default=0)),
                ('turnback_adult', models.IntegerField(default=0)),
                ('in_child', models.IntegerField(default=0)),
                ('out_child', models.IntegerField(default=0)),
                ('passby_child', models.IntegerField(default=0)),
                ('turnback_child', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CleanIndicatorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_clean', models.BooleanField(default=False)),
                ('annotator_status', models.CharField(blank=True, choices=[('', ''), ('garbage', 'garbage')], default='', max_length=10)),
                ('is_annotated', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clean_indicator_history/%Y/%m/%d/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clean_indicator_histories', to='camera.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_statuses', to='camera.cameratype')),
            ],
        ),
        migrations.CreateModel(
            name='CameraHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sn', models.CharField(max_length=255)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address_method', models.CharField(blank=True, max_length=255, null=True)),
                ('host_name', models.CharField(blank=True, max_length=255, null=True)),
                ('time_zone', models.IntegerField(blank=True, null=True)),
                ('hw_platform', models.CharField(blank=True, max_length=255, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeat', to='camera.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuffetViolationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('violation', models.BooleanField(default=False)),
                ('violation_list', models.JSONField(blank=True, null=True)),
                ('annotator_status', models.JSONField(blank=True, null=True)),
                ('is_annotated', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='buffet_violation_history/%Y/%m/%d/')),
                ('from_human', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buffet_violation_histories', to='camera.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BathroomMonitoringHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleaner_count', models.IntegerField(default=0)),
                ('present', models.BooleanField(default=False)),
                ('annotator_status', models.CharField(blank=True, choices=[('absent', 'absent'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='', max_length=10)),
                ('is_annotated', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bathroom_monitoring_history/%Y/%m/%d/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom_monitoring_histories', to='camera.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
