# Generated by Django 4.2 on 2025-05-23 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camera', '0002_alter_camera_type_alter_cameratype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanindicatorhistory',
            name='annotator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clean_indicator_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
