# Generated by Django 4.2 on 2025-05-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_cleanindicatorhistory_annotator'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenviolationreport',
            name='current_status',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleanindicatorhistory',
            name='annotator_status',
            field=models.CharField(blank=True, choices=[('clean', 'clean'), ('garbage', 'garbage')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='garbagemonitoringreport',
            name='annotator_status',
            field=models.CharField(blank=True, choices=[('clean', 'clean'), ('garbage', 'garbage')], default='', max_length=10),
        ),
    ]
