# Generated by Django 4.2 on 2025-05-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_kitchenviolationreport_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroommonitoringhistory',
            name='current_status',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buffetviolationreport',
            name='current_status',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanindicatorhistory',
            name='current_status',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garbagemonitoringreport',
            name='current_status',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardpresencehistory',
            name='current_status',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='current_status',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
