# Generated by Django 4.2 on 2025-05-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_bathroommonitoringhistory_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraheartbeat',
            name='status_log',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
