# Generated by Django 4.2 on 2025-05-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0006_cameraheartbeat_status_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='sn',
            field=models.CharField(max_length=255),
        ),
    ]
