# Generated by Django 4.2 on 2025-05-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_alter_camera_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterhistory',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='counter_image/%Y/%m/%d/'),
        ),
    ]
