# Generated by Django 4.2 on 2025-05-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0008_counterhistory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameratype',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cameratype',
            name='name_ar',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='camera',
            name='type',
            field=models.CharField(choices=[('clean', 'clean'), ('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount')], default='guard', max_length=255),
        ),
        migrations.DeleteModel(
            name='CleanIndicatorHistory',
        ),
    ]
