# Generated by Django 4.2 on 2025-05-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_cameratype_name_cameratype_name_ar_alter_camera_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount')], default='guard', max_length=255),
        ),
        migrations.AlterField(
            model_name='cameratype',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount')], max_length=255, unique=True),
        ),
    ]
