# Generated by Django 4.2 on 2025-05-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0010_alter_camera_type_alter_cameratype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffetviolationreport',
            name='ai_annotation_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='buffetviolationreport',
            name='is_ai_annotated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='ai_annotated',
            field=models.BooleanField(default=False),
        ),
    ]
