# Generated by Django 4.2 on 2025-05-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0011_buffetviolationreport_ai_annotation_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentimentanalysis',
            old_name='ai_annotated',
            new_name='is_ai_annotated',
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='ai_annotation_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
