# Generated by Django 4.2 on 2025-06-01 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camera', '0013_bathroommonitoringhistory_annotator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroommonitoringhistory',
            name='annotator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bath_monitor_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buffetviolationreport',
            name='annotator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buffet_violation_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='garbagemonitoringreport',
            name='annotator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garbage_monitor_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guardpresencehistory',
            name='annotator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guard_presence_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kitchenviolationreport',
            name='annotator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_violation_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='annotator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentiment_analysis_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
