# Generated by Django 4.2 on 2025-06-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0014_alter_bathroommonitoringhistory_annotator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroommonitoringhistory',
            name='annotator_status',
            field=models.CharField(blank=True, choices=[('absent', 'absent'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='guardpresencehistory',
            name='annotator_status',
            field=models.CharField(blank=True, choices=[('absent', 'absent'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='absent', max_length=10),
        ),
    ]
