# Generated by Django 4.2 on 2025-06-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0015_alter_bathroommonitoringhistory_annotator_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraheartbeat',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
