# Generated by Django 4.2 on 2025-06-05 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0017_alter_bathroommonitoringhistory_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentimentanalysis',
            old_name='sentiment_list_annotator',
            new_name='annotator_status',
        ),
    ]
