# Generated by Django 4.2 on 2025-06-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0018_rename_sentiment_list_annotator_sentimentanalysis_annotator_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentanalysis',
            name='current_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
