# Generated by Django 4.2 on 2025-06-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0019_sentimentanalysis_current_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroommonitoringhistory',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buffetviolationreport',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='garbagemonitoringreport',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guardpresencehistory',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchenviolationreport',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
