# Generated by Django 4.2 on 2025-06-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0020_bathroommonitoringhistory_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagemonitoringreport',
            name='ai_annotation_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='garbagemonitoringreport',
            name='is_ai_annotated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guardpresencehistory',
            name='ai_annotation_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='guardpresencehistory',
            name='is_ai_annotated',
            field=models.BooleanField(default=False),
        ),
    ]
