# Generated by Django 4.2 on 2025-12-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0022_aggfviolationreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount'), ('employeeactivity', 'employeeactivity')], default='guard', max_length=255),
        ),
        migrations.AlterField(
            model_name='cameratype',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount'), ('employeeactivity', 'employeeactivity')], max_length=255, unique=True),
        ),
    ]
