# Generated by Django 4.2 on 2025-12-15 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camera', '0023_alter_camera_type_alter_cameratype_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmookingViolationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('violation', models.BooleanField(default=False)),
                ('violation_list', models.JSONField(blank=True, null=True)),
                ('annotator_status', models.JSONField(blank=True, null=True)),
                ('current_status', models.JSONField(blank=True, null=True)),
                ('is_annotated', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='smooking_violation_history/%Y/%m/%d/')),
                ('annotator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smooking_violation_history', to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smooking_violation_histories', to='camera.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
