# Generated by Django 4.2 on 2025-12-24 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camera', '0025_alter_camera_type_alter_cameratype_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmokingViolationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('violation', models.BooleanField(default=False)),
                ('violation_list', models.JSONField(blank=True, null=True)),
                ('annotator_status', models.JSONField(blank=True, null=True)),
                ('current_status', models.JSONField(blank=True, null=True)),
                ('is_annotated', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='smoking_violation_history/%Y/%m/%d/')),
                ('annotator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smoking_violation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='camera',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount'), ('employeeactivity', 'employeeactivity'), ('smoking', 'smoking')], default='guard', max_length=255),
        ),
        migrations.AlterField(
            model_name='cameratype',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount'), ('employeeactivity', 'employeeactivity'), ('smoking', 'smoking')], max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='SmookingViolationReport',
        ),
        migrations.AddField(
            model_name='smokingviolationreport',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smoking_violation_histories', to='camera.camera'),
        ),
    ]
