# Generated by Django 4.2 on 2026-01-17 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camera', '0027_alter_camera_type_alter_cameratype_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facedetectionreport',
            name='annotator_status',
        ),
        migrations.RemoveField(
            model_name='facedetectionreport',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='facedetectionreport',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='facedetectionreport',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='facedetectionreport',
            name='violation',
        ),
        migrations.RemoveField(
            model_name='facedetectionreport',
            name='violation_list',
        ),
        migrations.AddField(
            model_name='facedetectionreport',
            name='name',
            field=models.CharField(blank=True, help_text='Recognized person name from camera', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facedetectionreport',
            name='time',
            field=models.DateTimeField(blank=True, help_text='Time when face was detected', null=True),
        ),
        migrations.AlterField(
            model_name='facedetectionreport',
            name='annotator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_detection_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
