# Generated by Django 4.2 on 2026-02-21 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camera', '0028_remove_facedetectionreport_annotator_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolenceMonitoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_violence', models.BooleanField(default=False)),
                ('annotator_status', models.CharField(blank=True, choices=[('non_violence', 'non-violence'), ('violence', 'violence')], default='', max_length=15)),
                ('is_annotated', models.BooleanField(default=False)),
                ('is_ai_annotated', models.BooleanField(default=False)),
                ('ai_annotation_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('current_status', models.JSONField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='violence_monitoring_history/%Y/%m/%d/')),
                ('annotator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violence_monitor_history', to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violence_monitoring_histories', to='camera.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FallDetectionMonitoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_fall_detected', models.BooleanField(default=False)),
                ('annotator_status', models.CharField(blank=True, choices=[('not_detected', 'not detected'), ('fall_detected', 'fall detected')], default='', max_length=15)),
                ('is_annotated', models.BooleanField(default=False)),
                ('is_ai_annotated', models.BooleanField(default=False)),
                ('ai_annotation_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('current_status', models.JSONField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fall_detection_monitoring_history/%Y/%m/%d/')),
                ('annotator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fall_detection_monitor_history', to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fall_detection_monitoring_histories', to='camera.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrowdMonitoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_crowd', models.BooleanField(default=False)),
                ('annotator_status', models.CharField(blank=True, choices=[('warn', 'warn'), ('high', 'high')], default='', max_length=15)),
                ('is_annotated', models.BooleanField(default=False)),
                ('is_ai_annotated', models.BooleanField(default=False)),
                ('ai_annotation_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('current_status', models.JSONField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crowd_monitoring_history/%Y/%m/%d/')),
                ('annotator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crowd_monitor_history', to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_monitoring_histories', to='camera.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
