# Generated by Django 4.2 on 2026-02-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0029_violencemonitoringreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount'), ('employeeactivity', 'employeeactivity'), ('smoking', 'smoking'), ('facedetection', 'facedetection'), ('falldetection', 'falldetection'), ('violencedetection', 'violencedetection'), ('crowdmonitoring', 'crowdmonitoring')], default='guard', max_length=255),
        ),
        migrations.AlterField(
            model_name='cameratype',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount'), ('employeeactivity', 'employeeactivity'), ('smoking', 'smoking'), ('facedetection', 'facedetection'), ('falldetection', 'falldetection'), ('violencedetection', 'violencedetection'), ('crowdmonitoring', 'crowdmonitoring')], max_length=255, unique=True),
        ),
    ]
