# Generated by Django 4.2 on 2026-03-01 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camera', '0030_alter_camera_type_alter_cameratype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount'), ('employeeactivity', 'employeeactivity'), ('smoking', 'smoking'), ('facedetection', 'facedetection'), ('falldetection', 'falldetection'), ('violencedetection', 'violencedetection'), ('crowdmonitoring', 'crowdmonitoring'), ('climbmonitoring', 'climbmonitoring')], default='guard', max_length=255),
        ),
        migrations.AlterField(
            model_name='cameratype',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount'), ('employeeactivity', 'employeeactivity'), ('smoking', 'smoking'), ('facedetection', 'facedetection'), ('falldetection', 'falldetection'), ('violencedetection', 'violencedetection'), ('crowdmonitoring', 'crowdmonitoring'), ('climbmonitoring', 'climbmonitoring')], max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='WallClimbMonitoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_climb', models.BooleanField(default=False)),
                ('annotator_status', models.CharField(blank=True, choices=[('no_climb', 'no_climb'), ('climb', 'climb')], default='', max_length=15)),
                ('is_annotated', models.BooleanField(default=False)),
                ('is_ai_annotated', models.BooleanField(default=False)),
                ('ai_annotation_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('current_status', models.JSONField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wall_climb_monitoring_history/%Y/%m/%d/')),
                ('annotator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wall_climb_monitor_history', to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_climb_monitoring_histories', to='camera.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
