# Generated by Django 4.2 on 2026-03-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0032_alter_camera_type_alter_cameratype_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount'), ('employeeactivity', 'employeeactivity'), ('smoking', 'smoking'), ('facedetection', 'facedetection'), ('falldetection', 'falldetection'), ('violencedetection', 'violencedetection'), ('crowdmonitoring', 'crowdmonitoring'), ('climbmonitoring', 'climbmonitoring'), ('abnormalactivity', 'abnormalactivity'), ('livestream', 'livestream')], default='guard', max_length=255),
        ),
        migrations.AlterField(
            model_name='cameratype',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount'), ('employeeactivity', 'employeeactivity'), ('smoking', 'smoking'), ('facedetection', 'facedetection'), ('falldetection', 'falldetection'), ('violencedetection', 'violencedetection'), ('crowdmonitoring', 'crowdmonitoring'), ('climbmonitoring', 'climbmonitoring'), ('abnormalactivity', 'abnormalactivity'), ('livestream', 'livestream')], max_length=255, unique=True),
        ),
    ]
