# Generated by Django 4.2 on 2026-05-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0033_alter_camera_type_alter_cameratype_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='abnormalactivities',
            index=models.Index(condition=models.Q(('image__isnull', False), ('is_rejected', False), models.Q(('image', ''), _negated=True)), fields=['camera', 'is_annotated', '-created_at'], name='abnormal_gal_idx'),
        ),
        migrations.AddIndex(
            model_name='aggfviolationreport',
            index=models.Index(condition=models.Q(('image__isnull', False), ('is_rejected', False), models.Q(('image', ''), _negated=True)), fields=['camera', 'is_annotated', '-created_at'], name='aggf_gal_idx'),
        ),
        migrations.AddIndex(
            model_name='bathroommonitoringhistory',
            index=models.Index(condition=models.Q(('image__isnull', False), ('is_rejected', False), models.Q(('image', ''), _negated=True)), fields=['camera', 'is_annotated', '-created_at'], name='bath_gal_idx'),
        ),
        migrations.AddIndex(
            model_name='buffetviolationreport',
            index=models.Index(condition=models.Q(('image__isnull', False), ('is_rejected', False), models.Q(('image', ''), _negated=True)), fields=['camera', 'is_annotated', '-created_at'], name='buffet_gal_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['tent', 'type'], name='cam_tent_type_idx'),
        ),
        migrations.AddIndex(
            model_name='crowdmonitoringreport',
            index=models.Index(condition=models.Q(('image__isnull', False), ('is_rejected', False), models.Q(('image', ''), _negated=True)), fields=['camera', 'is_annotated', '-created_at'], name='crowd_gal_idx'),
        ),
        migrations.AddIndex(
            model_name='facedetectionreport',
            index=models.Index(condition=models.Q(('image__isnull', False), ('is_rejected', False), models.Q(('image', ''), _negated=True)), fields=['camera', 'is_annotated', '-created_at'], name='face_gal_idx'),
        ),
        migrations.AddIndex(
            model_name='falldetectionmonitoringreport',
            index=models.Index(condition=models.Q(('image__isnull', False), ('is_rejected', False), models.Q(('image', ''), _negated=True)), fields=['camera', 'is_annotated', '-created_at'], name='fall_gal_idx'),
        ),
        migrations.AddIndex(
            model_name='garbagemonitoringreport',
            index=models.Index(condition=models.Q(('image__isnull', False), ('is_rejected', False), models.Q(('image', ''), _negated=True)), fields=['camera', 'is_annotated', '-created_at'], name='garbage_gal_idx'),
        ),
        migrations.AddIndex(
            model_name='guardpresencehistory',
            index=models.Index(condition=models.Q(('image__isnull', False), ('is_rejected', False), models.Q(('image', ''), _negated=True)), fields=['camera', 'is_annotated', 'start_time', '-end_time'], name='guard_gal_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenviolationreport',
            index=models.Index(condition=models.Q(('image__isnull', False), ('is_rejected', False), models.Q(('image', ''), _negated=True)), fields=['camera', 'is_annotated', '-created_at'], name='kitchen_gal_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalysis',
            index=models.Index(condition=models.Q(('image__isnull', False), ('is_rejected', False), models.Q(('image', ''), _negated=True)), fields=['camera', 'is_annotated', '-created_at'], name='sentiment_gal_idx'),
        ),
        migrations.AddIndex(
            model_name='smokingviolationreport',
            index=models.Index(condition=models.Q(('image__isnull', False), ('is_rejected', False), models.Q(('image', ''), _negated=True)), fields=['camera', 'is_annotated', '-created_at'], name='smoking_gal_idx'),
        ),
        migrations.AddIndex(
            model_name='violencemonitoringreport',
            index=models.Index(condition=models.Q(('image__isnull', False), ('is_rejected', False), models.Q(('image', ''), _negated=True)), fields=['camera', 'is_annotated', '-created_at'], name='violence_gal_idx'),
        ),
        migrations.AddIndex(
            model_name='wallclimbmonitoringreport',
            index=models.Index(condition=models.Q(('image__isnull', False), ('is_rejected', False), models.Q(('image', ''), _negated=True)), fields=['camera', 'is_annotated', '-created_at'], name='wall_gal_idx'),
        ),
    ]
