# Generated by Django 4.2 on 2026-05-19 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camera', '0034_abnormalactivities_abnormal_gal_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('recycle', 'recycle'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount'), ('employeeactivity', 'employeeactivity'), ('smoking', 'smoking'), ('facedetection', 'facedetection'), ('falldetection', 'falldetection'), ('violencedetection', 'violencedetection'), ('crowdmonitoring', 'crowdmonitoring'), ('climbmonitoring', 'climbmonitoring'), ('abnormalactivity', 'abnormalactivity'), ('livestream', 'livestream')], default='guard', max_length=255),
        ),
        migrations.AlterField(
            model_name='cameratype',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('recycle', 'recycle'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount'), ('employeeactivity', 'employeeactivity'), ('smoking', 'smoking'), ('facedetection', 'facedetection'), ('falldetection', 'falldetection'), ('violencedetection', 'violencedetection'), ('crowdmonitoring', 'crowdmonitoring'), ('climbmonitoring', 'climbmonitoring'), ('abnormalactivity', 'abnormalactivity'), ('livestream', 'livestream')], max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='RecycleMonitoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_clean', models.BooleanField(default=False)),
                ('annotator_status', models.CharField(blank=True, choices=[('clean', 'clean'), ('recycle', 'recycle')], default='', max_length=10)),
                ('is_annotated', models.BooleanField(default=False)),
                ('is_ai_annotated', models.BooleanField(default=False)),
                ('ai_annotation_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('current_status', models.JSONField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recycle_monitoring_history/%Y/%m/%d/')),
                ('annotator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycle_monitor_history', to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycle_monitoring_histories', to='camera.camera')),
            ],
        ),
        migrations.AddIndex(
            model_name='recyclemonitoringreport',
            index=models.Index(condition=models.Q(('image__isnull', False), ('is_rejected', False), models.Q(('image', ''), _negated=True)), fields=['camera', 'is_annotated', '-created_at'], name='recycle_gal_idx'),
        ),
    ]
