# Generated by Django 4.2 on 2026-05-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0037_add_recycle_violation_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdmonitoringreport',
            name='annotator_status',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('orange', 'orange'), ('green', 'green')], default='', max_length=15),
        ),
    ]
