# Generated by Django 4.2 on 2026-05-26 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camera', '0039_cleanerspresencehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanerspresencehistory',
            name='annotator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaners_presence_annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleanerspresencehistory',
            name='annotator_status',
            field=models.CharField(blank=True, choices=[('cleaner-female', 'Cleaner Female'), ('cleaner-male', 'Cleaner Male'), ('supervisor-female', 'Supervisor Female'), ('supervisor-male', 'Supervisor Male')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cleanerspresencehistory',
            name='is_annotated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cleanerspresencehistory',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='abnormalactivities',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='aggfviolationreport',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bathroommonitoringhistory',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='buffetviolationreport',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('recycle', 'recycle'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount'), ('employeeactivity', 'employeeactivity'), ('smoking', 'smoking'), ('facedetection', 'facedetection'), ('falldetection', 'falldetection'), ('violencedetection', 'violencedetection'), ('crowdmonitoring', 'crowdmonitoring'), ('climbmonitoring', 'climbmonitoring'), ('abnormalactivity', 'abnormalactivity'), ('livestream', 'livestream'), ('cleaners', 'cleaners')], default='guard', max_length=255),
        ),
        migrations.AlterField(
            model_name='cameraheartbeat',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cameratype',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('recycle', 'recycle'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount'), ('employeeactivity', 'employeeactivity'), ('smoking', 'smoking'), ('facedetection', 'facedetection'), ('falldetection', 'falldetection'), ('violencedetection', 'violencedetection'), ('crowdmonitoring', 'crowdmonitoring'), ('climbmonitoring', 'climbmonitoring'), ('abnormalactivity', 'abnormalactivity'), ('livestream', 'livestream'), ('cleaners', 'cleaners')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='counterhistory',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='crowdmonitoringreport',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='facedetectionreport',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='falldetectionmonitoringreport',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='garbagemonitoringreport',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='guardpresencehistory',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitchenimage',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitchenviolationreport',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='recyclemonitoringreport',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='smokingviolationreport',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='violencemonitoringreport',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallclimbmonitoringreport',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='cleanerspresencehistory',
            index=models.Index(fields=['camera', '-start_time'], name='cleaners_cam_start_idx'),
        ),
        migrations.AddIndex(
            model_name='counterhistory',
            index=models.Index(fields=['camera', 'end_time'], name='counter_cam_end_idx'),
        ),
    ]
