# Generated by Django 4.2 on 2026-05-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0040_cleanerspresencehistory_annotator_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='abnormalactivities',
            index=models.Index(fields=['is_annotated', 'is_rejected', 'created_at'], name='abnormal_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='aggfviolationreport',
            index=models.Index(fields=['is_annotated', 'is_rejected', 'created_at'], name='aggf_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='bathroommonitoringhistory',
            index=models.Index(fields=['is_annotated', 'is_rejected', 'created_at'], name='bath_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='buffetviolationreport',
            index=models.Index(fields=['is_annotated', 'is_rejected', 'created_at'], name='buffet_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='counterhistory',
            index=models.Index(fields=['camera', 'created_at'], name='counter_cam_created_idx'),
        ),
        migrations.AddIndex(
            model_name='crowdmonitoringreport',
            index=models.Index(fields=['is_annotated', 'is_rejected', 'created_at'], name='crowd_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='falldetectionmonitoringreport',
            index=models.Index(fields=['is_annotated', 'is_rejected', 'created_at'], name='fall_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='garbagemonitoringreport',
            index=models.Index(fields=['is_annotated', 'is_rejected', 'created_at'], name='garbage_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='guardpresencehistory',
            index=models.Index(fields=['is_annotated', 'is_rejected', 'created_at'], name='guard_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenviolationreport',
            index=models.Index(fields=['is_annotated', 'is_rejected', 'created_at'], name='kitchen_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='recyclemonitoringreport',
            index=models.Index(fields=['is_annotated', 'is_rejected', 'created_at'], name='recycle_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalysis',
            index=models.Index(fields=['is_annotated', 'is_rejected', 'created_at'], name='sentiment_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='smokingviolationreport',
            index=models.Index(fields=['is_annotated', 'is_rejected', 'created_at'], name='smoking_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='violencemonitoringreport',
            index=models.Index(fields=['is_annotated', 'is_rejected', 'created_at'], name='violence_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='wallclimbmonitoringreport',
            index=models.Index(fields=['is_annotated', 'is_rejected', 'created_at'], name='wall_acc_idx'),
        ),
    ]
