# Generated by Django 4.2 on 2025-05-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sn', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.CharField(blank=True, max_length=255, null=True)),
                ('long', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('top', models.FloatField(blank=True, null=True)),
                ('left', models.FloatField(blank=True, null=True)),
                ('online', models.BooleanField(default=False)),
                ('tempareture', models.FloatField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('last_entry_time', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('environment', 'environment'), ('weight', 'weight')], default='environment', max_length=255)),
                ('tent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='tent.tent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SensorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnvironmentSensorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tempareture', models.FloatField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('last_entry_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.environmentsensor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
