# Generated by Django 4.2 on 2025-06-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environmentsensor',
            options={'ordering': ['sn']},
        ),
    ]
