# Generated by Django 4.2 on 2025-06-06 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_alter_environmentsensor_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentsensor',
            name='check_neighbour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environmentsensor',
            name='neighbour_name_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighbour_1_of', to='sensor.environmentsensor', verbose_name='Neighbour Name 1'),
        ),
        migrations.AddField(
            model_name='environmentsensor',
            name='neighbour_name_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighbour_2_of', to='sensor.environmentsensor', verbose_name='Neighbour Name 2'),
        ),
        migrations.AddField(
            model_name='environmentsensor',
            name='neighbour_name_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighbour_3_of', to='sensor.environmentsensor', verbose_name='Neighbour Name 3'),
        ),
        migrations.AddField(
            model_name='environmentsensorrecord',
            name='update_from_neighbour',
            field=models.BooleanField(default=False),
        ),
    ]
