# Generated by Django 4.2 on 2026-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_environmentsensor_check_neighbour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentsensor',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentsensorrecord',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorlocation',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='environmentsensorrecord',
            index=models.Index(fields=['sensor', '-created_at'], name='envsensrec_sensor_created_idx'),
        ),
    ]
