# Generated by Django 4.2 on 2025-05-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0001_initial'),
        ('tent', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='assigned_tent',
            field=models.ManyToManyField(blank=True, to='tent.tent'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='camera_type_annotator',
            field=models.ManyToManyField(blank=True, to='camera.cameratype'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authentication.company'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='company_annotator',
            field=models.ManyToManyField(blank=True, to='authentication.company'),
        ),
    ]
