# Generated by Django 4.2 on 2025-05-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_bathrooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_bathrooms',
            field=models.BooleanField(default=False),
        ),
    ]
