# Generated by Django 4.2 on 2025-05-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_company_is_bathrooms_myuser_is_bathrooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='is_bathrooms',
            new_name='is_peoplecount',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='is_bathrooms',
            new_name='is_peoplecount',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_environment_sensor',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_garbage',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_headcount',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_environment_sensor',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_garbage',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_headcount',
        ),
    ]
