# Generated by Django 4.2 on 2025-05-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_is_bathrooms_company_is_peoplecount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='company_fav_icon/'),
        ),
    ]
