# Generated by Django 4.2 on 2025-05-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_company_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
