# Generated by Django 4.2 on 2025-05-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_company_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_sensor_assign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_sensor_assign',
            field=models.BooleanField(default=False),
        ),
    ]
