# Generated by Django 4.2 on 2025-06-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_company_is_sensor_assign_myuser_is_sensor_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_annotator_ranking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_annotator_ranking',
            field=models.BooleanField(default=False),
        ),
    ]
