# Generated by Django 4.2 on 2025-06-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_company_is_annotator_ranking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_settings',
            field=models.BooleanField(default=False),
        ),
    ]
