# Generated by Django 4.2 on 2025-12-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_company_created_at_alter_company_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_aggf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_aggf',
            field=models.BooleanField(default=False),
        ),
    ]
