# Generated by Django 4.2 on 2025-12-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_company_is_aggf_myuser_is_aggf'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_smooking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_smooking',
            field=models.BooleanField(default=False),
        ),
    ]
