# Generated by Django 4.2 on 2025-12-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_company_is_smooking_myuser_is_smooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='is_smooking',
            new_name='is_smoking',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='is_smooking',
            new_name='is_smoking',
        ),
    ]
