# Generated by Django 4.2 on 2026-01-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_rename_is_smooking_company_is_smoking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_face_detection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_face_detection',
            field=models.BooleanField(default=False),
        ),
    ]
