# Generated by Django 4.2 on 2026-02-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_company_is_face_detection_myuser_is_face_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_crowdmonitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_falldetection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_violencedetection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_crowdmonitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_falldetection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_violencedetection',
            field=models.BooleanField(default=False),
        ),
    ]
