# Generated by Django 4.2 on 2026-03-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_company_is_crowdmonitoring_company_is_falldetection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_climbmonitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_climbmonitoring',
            field=models.BooleanField(default=False),
        ),
    ]
