# Generated by Django 4.2 on 2026-03-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_company_is_climbmonitoring_myuser_is_climbmonitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_abnormalactivity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_abnormalactivity',
            field=models.BooleanField(default=False),
        ),
    ]
