# Generated by Django 4.2 on 2026-03-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_company_is_abnormalactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_livestream',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_livestream',
            field=models.BooleanField(default=False),
        ),
    ]
