# Generated by Django 4.2 on 2026-05-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_company_is_livestream_myuser_is_livestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_can_delete_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_recycle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_can_delete_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_recycle',
            field=models.BooleanField(default=False),
        ),
    ]
