# Generated by Django 4.2 on 2026-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_company_is_cleaners_presence_myuser_is_cleaners_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
