# Generated by Django 4.2 on 2025-05-21 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('location', models.TextField(blank=True, null=True)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('tent_image', models.ImageField(blank=True, null=True, upload_to='images_tent/%Y/%m/%d/')),
                ('air_condition', models.IntegerField(blank=True, null=True)),
                ('air_condition_update_time', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('staying', models.IntegerField(default=0)),
                ('is_arafa', models.BooleanField(default=False)),
                ('adjust', models.IntegerField(default=0)),
                ('fixed', models.BooleanField(default=False)),
                ('max_adjust_tempareture', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avg_adjust_tempareture', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('min_adjust_tempareture', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_adjust_tempareture', models.BooleanField(default=False)),
                ('max_adjust_humidity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avg_adjust_humidity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('min_adjust_humidity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_adjust_humidity', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tent', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nationality', models.ManyToManyField(blank=True, to='tent.country')),
            ],
        ),
        migrations.CreateModel(
            name='TentsWaterTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tank_number', models.CharField(max_length=255, unique=True)),
                ('sensor_sn', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_tanks', to='tent.tent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterTankSensorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('water_level', models.FloatField(blank=True, null=True)),
                ('water_level_percent', models.FloatField(blank=True, null=True)),
                ('online', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('water_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_history', to='tent.tentswatertank')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TentAirQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('air_quality', models.IntegerField()),
                ('tent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tent.tent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='tent',
            constraint=models.UniqueConstraint(fields=('company', 'name', 'is_arafa'), name='unique_company_tent_name'),
        ),
    ]
