# Generated by Django 4.2 on 2026-05-09 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '__first__'),
        ('camera', '__first__'),
        ('tent', '__first__'),
        ('access_point', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrangePiDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('mac_address', models.CharField(help_text='Format: AA:BB:CC:DD:EE:FF', max_length=17, unique=True)),
                ('port', models.IntegerField(default=8000)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orangepi_devices', to='authentication.company')),
                ('tent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orangepi_devices', to='tent.tent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('camera', 'Camera'), ('orange_pi', 'Orange Pi'), ('access_point', 'Access Point')], max_length=20)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('details', models.TextField(blank=True, null=True)),
                ('access_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='access_point.router')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='camera.camera')),
                ('orange_pi_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='technical_dashboard.orangepidevice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='deviceactivitylog',
            index=models.Index(fields=['device_type', 'timestamp'], name='technical_d_device__35d439_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceactivitylog',
            index=models.Index(fields=['device_type', 'camera'], name='technical_d_device__76df09_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceactivitylog',
            index=models.Index(fields=['device_type', 'orange_pi_device'], name='technical_d_device__513a64_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceactivitylog',
            index=models.Index(fields=['device_type', 'access_point'], name='technical_d_device__cbaa85_idx'),
        ),
    ]
