# Generated by Django 4.2 on 2026-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_dashboard', '0002_add_online_to_orangepidevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceactivitylog',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='orangepidevice',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
